VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "atango_ubuntu1404"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "2560"]
  end
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/kuhaku/atango/master/setup/provision_root.sh"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/kuhaku/atango/master/setup/provision_node.sh", :privileged => false
end
